# Runs tests on any push or pull request.
# If the tests pass and this is a push to the main branch also run Semantic Release.
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
