# Run `npm run fix` on any push or pull request.
# If changes were made and the tests pass, commit the changes back.
name: Fix
on: [push, pull_request, workflow_dispatch]
jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - shell: bash
        env:
          BOT_USER_NAME: ${{ secrets.BOT_USER_NAME }}
          BOT_USER_ID: ${{ secrets.BOT_USER_ID }}
          BOT_PUBLIC_KEY: ${{ secrets.BOT_PUBLIC_KEY }}
          BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${BOT_PRIVATE_KEY}"
          git config user.name "${BOT_USER_NAME}"
          git config user.email "${BOT_USER_ID}+${BOT_USER_NAME}@users.noreply.github.com"
          git config --global gpg.format ssh
          git config --global user.signingkey "key::${SSH_PUBLIC_KEY}"
          npm ci
          npm run fix
          git commit -am 'style: npm run fix' && git push origin main
